print("hello world")
print("goodbye world")
print("loy")
print("toy")
print("bonjour world")
print("au revoir")
print("salut")
print("hello world")
print("hello world")
print("hello world")
print("hello world")
print("hello world")
print("hello world")
print("hello world")
print("hello world")

